version: '3'
# volumes:
#   nedum-folder:
networks:
  nedum-network:


services:

  postgres:
    container_name:  nedum-postgress
    image: postgres
    networks:
      - nedum-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Fitb@123

  java-maven-app:
    container_name: nedum-java-maven-app
    image: nedumdocker/maven-java-nana:1.1.7-71
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - nedum-network
